# Generated by Django 4.1.3 on 2022-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=100),
        ),
    ]
