# Generated by Django 4.1.3 on 2022-12-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0002_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
