# Generated by Django 4.1.3 on 2022-12-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
