# Generated by Django 4.1.3 on 2022-12-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
