# Generated by Django 4.1.3 on 2022-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
