# Generated by Django 4.1.3 on 2022-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0010_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
