# Generated by Django 4.1.3 on 2022-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Api', '0012_alter_account_email_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
