# Generated by Django 4.1.3 on 2022-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('city_p1', models.CharField(max_length=50)),
                ('city_p2', models.CharField(max_length=50)),
                ('city_p3', models.CharField(max_length=50)),
            ],
        ),
    ]
