# Generated by Django 4.1.3 on 2022-12-20 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Preferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='city_p1',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='city_p2',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='city_p3',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='username',
        ),
        migrations.AddField(
            model_name='preference',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preference',
            name='city_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
