# Generated by Django 4.1.3 on 2022-12-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='city_p1',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='city_p2',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='city_p3',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='username',
        ),
    ]
