# Generated by Django 4.1.3 on 2022-12-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preferences', '0002_remove_preference_city_p1_remove_preference_city_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='account',
        ),
    ]
